### ISSUE TITLE
expected 'double' but got 'float'

### ISSUE THREAD

**Issue by jasamarante** [adrn/SuperFreq#8]
Hello,

I have an orbit calculated using agama package. I then try to calculate its frequencies using superfreq.find_fundamental_frequencies(). 
However I get this error message: 

>  Buffer dtype mismatch, expected 'double' but got 'float'

I already tried to convert my vector of positions and velocities to 'double', using 
`pos = pos.astype("double")`

but I still get the same error.

Any clue with what is happening?

**Comment by adrn** [comment]
Hm, sorry you hit this error!

For context, would you mind sharing some of the code around the line you included above?

**Comment by jasamarante** [comment]
Hi,

` #integrates my orbit`

`times,points = agama.orbit(potential=pot, ic=[8,0,0,
                       -50,50,50], time=2, trajsize=5000)`

`xO = points[:,0]`
`yO = points[:,1]`
`zO = points[:,2]`
`vyO = calc_v(yO, dtime=dt, vel_init = 240)`
`vxO = calc_v(xO, dtime=dt, vel_init = 0)`
`vzO = calc_v(zO, dtime=dt, vel_init = 5) #simple function that gets the cartesian velocities`
`import superfreq as sf`
`superfreq = sf.SuperFreq(t=times) `
`complexX = xO+1j*vxO`
`complexY = yO+1j*vyO`
`complexZ = zO+1j*vzO`
`ORB = [complexX, complexY, complexZ]`
`superfreq.find_fundamental_frequencies(ORB)`

I have an working example given in Shanghai summer school this year. In that example, the orbits were calculated using gala package. The main difference is that in gala, the positions and velocities have this format:

`[<Quantity [0.02686991+0.j        ,0.02682044-0.00099027j,
            0.02667149-0.00199137j,...,0.70614843-0.33005395j,
            0.670524  -0.38162256j,0.62998607-0.42833259j]>,
 <Quantity [ 0.00782199+0.j        , 0.00780421-0.00035584j,
             0.0077507 -0.00071526j,...,-0.63323208+0.01199625j,
            -0.62908965+0.07037214j,-0.61925868+0.12572488j]>,
 <Quantity [ 1.13250488+0.j        , 1.12825114-0.08512433j,
             1.11546011-0.17084686j,...,-0.32382302-0.78908749j,
            -0.40004303-0.73376611j,-0.47029437-0.66997981j]>]`

While in my case I have a list of arrays. 
`[array([8.         +0.j        , 7.99945593 -1.33085266j,
        7.99782515 -3.9890588j , ..., 7.77188778+54.52296896j,
        7.79308033+51.8391022j , 7.81317377+49.15056988j]),
 array([ 0.        +240.j        ,  0.09599982+234.82518291j,
         0.1919519 +234.70839796j, ..., -2.19568467+227.4142596j ,
        -2.10242128+228.13159035j, -2.00887942+228.81276296j]),
 array([0.        +5.j        , 0.00198702+4.8604603j ,
        0.00394621+4.7923665j , ..., 0.0952256 +9.20129776j,
        0.09889825+8.9836564j , 0.10247888+8.75859752j])]`

**Comment by jasamarante** [comment]
Just in case anyone ever run into this problem. It is actually a simple solution.

Agama returns the orbits points (position, velocity)  and time arrays as "float32". Then one has to convert all of them to "double".  

Before I was only converting the only the positions and velocities but ignored the time array...

**Comment by eugvas** [comment]
now it is possible to specify data type explicitly when integrating an orbit in agama, e.g.

times,points = agama.orbit(potential=pot, ic=ic, time=time, trajsize=5000, dtype=complex)
result = SuperFreq(times).find_fundamental_frequencies(points.T)

btw, I find that in the current version of SuperFreq, the output of this routine is no longer a tuple of three objects "freqs, tbl, ix", but a single monolithic object of type "superfreq.core.SuperFreqResult", which is not unpacked into a tuple, contrary to the documentation and examples.
